### ISSUE TITLE
Better dump format for InlineExtent

### ISSUE THREAD

**Issue by asomers** [bfffs/bfffs#255]
When dumping the file system to YAML, InlineExtents get serialized as a long array of bytes, like this:
```yaml
            2-2-0000000007f000:
              InlineExtent:
                buf:
                  - 130
                  - 108
                  - 180
                  - 60
```
it would be better if they could be serialized as some kind of hex dump, like this:
```yaml
            2-2-0000000007f000:
              InlineExtent:
                buf:
                  - "00000000: 7573 6520 6e69 783a 3a73 7973 3a3a 7574  use nix::sys::ut"
                  - "00000010: 736e 616d 653a 3a75 6e61 6d65 3b0a 0a66  sname::uname;..f"
```
